### ISSUE TITLE
Impossible to write in the file directory /var/nextdata 

### ISSUE THREAD

**Issue by valentincauro** [zilexa/Homeserver#1]
Hi :)
Your docker compose file looks really powerfull..
But I've juste got a little problem for the install 
![image](https://user-images.githubusercontent.com/23341404/114463993-75235d00-9be5-11eb-8c4c-2f1a5489561a.png)

I think I did something wrong with the $DOCKERDIRECTORY variable, I'd just put "." to stay in my root directory (and be able to do data backup later)

Have you got an idea ? Thanks

**Comment by zilexa** [comment]
1) that message that is clearly a permissions + ownership + existence issue, nothing wrong with the nextcloud compose file. 
To solve: Make sure the directory exist, fix ownership + permissions of that dir AND its parent dir, delete the containers+non-persistent volumes and rerun your compose file. 

Then you have a few things you should verify before running compose up: 
1. use the "config" argument instead of up. (see my main docker compose file, the command at the top) to verify the actual path of your $DOCKERDIR).
2. Instead of that line in caddy you can use "volumes of" to be certain Caddy has access to everything it needs, this ensures the issue will not be with Caddy at all. 

```
I think I did something wrong with the $DOCKERDIRECTORY variable, I'd just put "." to stay in my root directory (and be able to do data backup later)
```
I don't really understand what you mean, could you elaborate?
In my case, the docker dir for persistent volumes is: `/home/username/docker` and each docker service has a subfolder in there, for example `/home/username/docker/nextcloud`. Why are you deviating from that? You can easily backup your $HOME dir (which is /home/username) or your docker dir (which is `/home/username/docker`).

If you are actually using /root, you have opened a can of worms and I can't really help you as permissions will be completely different, note you should not need to use /root and you should not need to use sudo when you run docker commands. 

The warning message is about permissions/ownership/folder not existing.
