### ISSUE TITLE
Low-Budget alternatives for Mainboards

### ISSUE THREAD

**Issue by Pferdebockwurst** [zilexa/Homeserver#16]
The prices for the Fujitsu D3417 and the D3644 are rising and their availability is worsening. Maybe there are newer and thus cheaper alternatives?

**Comment by zilexa** [comment]
Hi, yes there is new information in the forum I linked to, although the opening post is not updated yet. Also good data on energy consumption is missing but first data is promising. Since first post is not updated it is very time consuming to find the right info in this topic.
https://gathering.tweakers.net/forum/list_message/74041322
Also know that Kontron (took over Fujitsu mainboards) is releasing new motherboards this year to replace the recommended options. 

Your main isue will be if you find ECC memory important (like I do). I believe there are very little alternatives. DDR5 (if you choose to go for a latest gen Intel) does have some kind of ECC by default, but uncomparable. Haven't really looked into it. 

I am currently focused on testing the solution for the single remaining issue: Filerun/webDAV, clients (laptops, phones) resyncing all data when the filerun container is recreated or restarted.

**Comment by zilexa** [comment]
@Pferdebockwurst i just updated the link in my prev post to only show pinned posts in that Dutch forum. You will find options there.

**Comment by zilexa** [comment]
I will close this now but will leave a similar issue open as a reminder to myself to update the Hardware Recommendation page.
