### ISSUE TITLE
Filerun free isn't available for (new) users anymore

### ISSUE THREAD

**Issue by alex3305** [zilexa/Homeserver#26]
[Filerun](https://filerun.com/) free isn't available anymore. Unfortunately there aren't that many [good alternatives](https://alternativeto.net/software/filerun--file-manager/?platform=self-hosted). For my use case (photo sync) I replaced it with [Immich](https://github.com/immich-app/immich).

**Comment by zilexa** [comment]
Actually, Filerun is still available for personal use. 
Not all software should be free. Filerun is fantastic, unbeatable at many fronts. A huge amount of hours has been put in its development. So ofcourse, makes sense that comes with a reward.
Lots of free users wanted free support and became very demanding. So I totally understand the change. Especially since the new personal license is only a one-time fee of €99 and includes lifetime free updates. 
This license should not effect your current limit on # of users.
See here:
https://feedback.filerun.com/communities/1/topics/1849-sunsetting-the-free-filerun-version

I celebrate this change. We will get much more dedication, faster releases, big feature updates etc with this change.

**Comment by zilexa** [comment]
@alex3305 
The new non-enterprise Personal license is now added to the Filerun website: 
https://filerun.com/pricing
I tried Immich and its really promising for photos. But its not a file management webservice at all. So it does not compete with Filerun/NextCloud etc. Immich development is going fast, but I doubt it will ever go beyond its current scope. I will definitely add it to my Compose and this repository, not as Filerun alternative, but in addition to, probably after the northern hemisphere summer when I will have more time (and Immich is more stable).
